import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { VscGithubInverted, VscTwitter, VscLink } from "react-icons/vsc";
import Profile from "./profile";
export const siteTitle = "tatsushige.com";
import Header from "./header";

export default function Layout({
  children,
  home,
}: {
  children: React.ReactNode;
  home?: boolean;
}) {
  return (
    <div className="mx-auto max-w-xl font-sans mb-16 px-4">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/svg+xml" href="favicon.svg" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta
          property="og:image"
          content={`https://og-image.vercel.app/${encodeURI(
            siteTitle
          )}.png?theme=light&md=0&fontSize=75px&images=https%3A%2F%2Fassets.zeit.co%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg`}
        />
        <meta name="og:title" content={siteTitle} />
      </Head>
      <Header />
      <main>{children}</main>
    </div>
  );
}
